name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: ['1.20', '1.21', '1.22']
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Firebird
      run: |
        sudo apt install firebird3.0-server -y
        sudo cp _attic/firebird.conf /etc/firebird/3.0
        sudo systemctl restart firebird3.0
        sudo chmod 0664 /etc/firebird/3.0/SYSDBA.password
        grep '=' /etc/firebird/3.0/SYSDBA.password |sed 's/^/export /' >test_user.env

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        source test_user.env
        go test -v ./...
