name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: ['1.20', '1.21', '1.22']
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup FirebirdSQL container
      uses: juarezr/firebirdsql-github-action@v1.2.0
      with:
        version: '2.5-ss'
        isc_password: "masterkey"

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
